name: Go

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*
  pull_request:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5
        with:
          go-version: 1.22
          cache: true
      - uses: extractions/setup-just@v2
      - name: Tests
        run: |
          go test -v -race ./...
      - uses: ko-build/setup-ko@v0.6
      - name: Push to GHCR
        run: ko build -B ./cmd/server
      - name: Push main branch to GHCR
        if: github.ref_name == 'main'
        run: |
          ko build -B --platform linux/amd64,linux/arm/v8,linux/arm64 --tags ${{ github.ref_name }}
      - name: Push tag to GHCR
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          ko build -B --platform linux/amd64,linux/arm/v8,linux/arm64 --tags ${{ github.ref_name }}
